export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMONS_ID = "GET_POKEMONS_ID";
export const FILTER_POKEMONS_TYPES = "FILTER_POKEMONS_TYPES";
export const GET_POKEMONSNAME = "GET_POKEMONSNAME";
